import type { CooperativeCategory } from "@/types";

export const PREDEFINED_CATEGORIES: CooperativeCategory[] = [
  {
    id: "residential-apartment",
    name: "Residential Apartment",
    description: "Residential apartment complexes and housing cooperatives",
    isActive: true,
    sortOrder: 1,
    cooperativeCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "business-complex",
    name: "Business Complex",
    description: "Commercial buildings and business centers",
    isActive: true,
    sortOrder: 2,
    cooperativeCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "coworking-space",
    name: "Coworking Space",
    description: "Shared workspaces and coworking facilities",
    isActive: true,
    sortOrder: 3,
    cooperativeCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "student-housing",
    name: "Student Housing",
    description: "Student dormitories and residential facilities",
    isActive: true,
    sortOrder: 4,
    cooperativeCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "mixed-use",
    name: "Mixed Use",
    description: "Properties with both residential and commercial use",
    isActive: true,
    sortOrder: 5,
    cooperativeCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "industrial",
    name: "Industrial",
    description: "Warehouses, factories, and industrial facilities",
    isActive: true,
    sortOrder: 6,
    cooperativeCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "retail",
    name: "Retail",
    description: "Shopping centers and retail complexes",
    isActive: true,
    sortOrder: 7,
    cooperativeCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "hospitality",
    name: "Hospitality",
    description: "Hotels, hostels, and hospitality services",
    isActive: true,
    sortOrder: 8,
    cooperativeCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
